# Generated by Django 3.2.3 on 2021-06-08 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20210602_1839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watersources',
            old_name='canal',
            new_name='watersource_name',
        ),
        migrations.RemoveField(
            model_name='watersources',
            name='lake',
        ),
        migrations.RemoveField(
            model_name='watersources',
            name='rain',
        ),
        migrations.RemoveField(
            model_name='watersources',
            name='well',
        ),
    ]
